Repository cdktf/cdktf-repository-manager, pull requests merged in 2024-12, with the labels that each got.

#337 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#339 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#340 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#338 chore: upgrade Terraform to 1.10.3
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
  package.json
Labels: automated, dependencies

#343 revert: remove the addition of Dependabot security
  lib/repository.ts
Labels: automerge, auto-approve

#344 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#345 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve
