Repository cdktf/cdktf-repository-manager, pull requests merged in 2024-04, with the labels that each got.

#282 chore: disable required CLA checks
  lib/repository.ts
  main.ts
Labels: automerge, auto-approve

#283 chore(deps): upgrade dependencies
  .github/workflows/upgrade-node.yml
  package.json
  yarn.lock
Labels: dependencies

#284 chore: upgrade Terraform to 1.8.0
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
Labels: automated, dependencies

#286 chore: upgrade Terraform to 1.8.2
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
Labels: automated, dependencies
