Repository cdktf/cdktf-repository-manager, pull requests merged in 2025-01, with the labels that each got.

#346 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#347 chore: enable Dependabot security updates
  lib/repository.ts
Labels: automerge, auto-approve

#349 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#351 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#352 chore: upgrade Terraform to 1.10.4
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
  package.json
Labels: automerge, dependencies, auto-approve

#353 chore(ci): automate all the things
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/deprecate-provider.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-dependencies.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-node.yml
  .github/workflows/upgrade-repositories.yml
  .github/workflows/upgrade-terraform.yml
  package.json
  projenrc.template.js
  scripts/check-jsii-versions.js
  scripts/check-node-versions.js
  scripts/check-terraform-version.js
  yarn.lock
Labels: automerge, auto-approve

#354 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#355 chore: upgrade Terraform to 1.10.5
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
  package.json
Labels: automerge, dependencies, auto-approve

#356 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve

#357 chore(deps): upgrade jsii & typescript to v5.5
  package.json
  projenrc.template.js
  yarn.lock
Labels: automated, automerge, auto-approve
