Repository cdktf/cdktf-repository-manager, pull requests merged in 2025-06, with the labels that each got.

#382 chore: upgrade Terraform to 1.12.1
  .github/workflows/deploy-cdktf-stacks.yml
  .github/workflows/diff-cdktf-stacks.yml
  package.json
Labels: automated, dependencies

#394 chore(deps): upgrade ESLint to v9
  .eslintignore
  .gitignore
  eslint.config.js
  package.json
  yarn.lock
Labels: automerge, auto-approve

#398 chore(deps): upgrade dependencies for this repo only
  yarn.lock
Labels: automerge, dependencies, auto-approve
